### ISSUE TITLE
Item Pickups

### ISSUE THREAD

**Issue by calebeno** [kateisprettydamngreat/Magicite-Decompiled#33]
Items need a representation in game.  
- An item in the game world can be a stack.
- When an item connects with the player it should attempt to add the item to the inventory.
  - If there is an available slot, the item will be deleted.
  - If there is an available slot, but there is not enough room for the entire item stack, only those which can be added will be, and then the rest will remain in the stack.
  - If there is no available slot, the item will remain in the world but will continue to check for the player having open inventory slots as long as it is connecting with the player. (but should not happen every single update frame)
- Items should only be spawned on the network by the server.
- The player can drop items from the inventory by clicking the item on empty screen space while the inventory is open.

**Comment by YewYew** [comment]
"When items are spawned from resources being interacted with (chop wood, mine rock) sets of local resources should be spawned for each player."

This may cause an overabundance of resources, and also enable players to "min-max" one character easily by pooling the resources gained.

More players already means more DPS and resource gathering speed.
